server:
  port: ${JOB_SERVICE_PORT:8081}

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://${JOB_SERVICE_DB_HOST:localhost}:${JOB_SERVICE_DB_PORT:5434}/${JOB_SERVICE_DB_NAME:job_service}
    username: ${JOB_SERVICE_DB_USERNAME:postgres}
    password: ${JOB_SERVICE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
