server:
  port: ${APPLICATION_SERVICE_PORT:8082}

spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://${APPLICATION_SERVICE_DB_HOST:localhost}:${APPLICATION_SERVICE_DB_PORT:5434}/${APPLICATION_SERVICE_DB_NAME:application_service}
    username: ${APPLICATION_SERVICE_DB_USERNAME:postgres}
    password: ${APPLICATION_SERVICE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

services:
  job-service:
    base-url: ${JOB_SERVICE_URL:http://localhost:8081}
  resume-parsing-service:
    base-url: ${RESUME_PARSING_SERVICE_URL:http://localhost:8084}
    read-timeout-ms: ${RESUME_PARSING_READ_TIMEOUT_MS:15000}
  ats-screening-service:
    base-url: ${ATS_SCREENING_SERVICE_URL:http://localhost:8085}

http-client:
  connect-timeout-ms: ${HTTP_CLIENT_CONNECT_TIMEOUT_MS:2000}
  read-timeout-ms: ${HTTP_CLIENT_READ_TIMEOUT_MS:3000}
