CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    job_id BIGINT NOT NULL,
    job_title VARCHAR(255),
    resume_url VARCHAR(1024),
    cover_letter_text VARCHAR(4000),
    status VARCHAR(50) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    years_of_experience INTEGER,
    match_score INTEGER,
    screening_notes VARCHAR(1000)
);

CREATE INDEX idx_applications_job_id ON applications(job_id);
CREATE INDEX idx_applications_status ON applications(status);

CREATE TABLE application_parsed_skills (
    application_id BIGINT NOT NULL REFERENCES applications(id),
    skill VARCHAR(255)
);

CREATE TABLE application_matched_skills (
    application_id BIGINT NOT NULL REFERENCES applications(id),
    skill VARCHAR(255)
);

CREATE TABLE application_missing_skills (
    application_id BIGINT NOT NULL REFERENCES applications(id),
    skill VARCHAR(255)
);
