CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    department VARCHAR(255),
    min_years_experience INTEGER,
    status VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE job_required_skills (
    job_id BIGINT NOT NULL REFERENCES jobs(id),
    skill VARCHAR(255)
);
