server:
  port: ${RESUME_STORAGE_SERVICE_PORT:8083}

spring:
  application:
    name: resume-storage-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:resumes}
